# 1) Write a program to read and print values of variables of different data types with their typea = input("string: ")
a = input("string: ")
b = int(input("int: "))
c = float(input("float: "))
print(a, b, c)
print(type(a), type(b), type(c))